"""add genre table

Revision ID: 706f61a2da38
Revises: a046d3afafd1
Create Date: 2019-11-06 20:44:33.293634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '706f61a2da38'
down_revision = 'a046d3afafd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lyric', sa.Column('genre_id', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'lyric', 'genre', ['genre_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lyric', type_='foreignkey')
    op.drop_column('lyric', 'genre_id')
    # ### end Alembic commands ###
